import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

interface AutocompleteItem {
  value: string;
  label: string;
}

type TranslationDictionary = Record<string, string>;

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const srcDir = join(__dirname, '..');

const LANGUAGES = ['en', 'ko', 'ja', 'ru'] as const;
type Language = typeof LANGUAGES[number];

async function fetchLanguageData(lang: string): Promise<AutocompleteItem[]> {
  const url = `https://tlidb.com/i18n/autocomplete_${lang}.json`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${lang} data: ${response.status} ${response.statusText}`);
  }
  return response.json();
}

console.log('Fetching translation data from tlidb.com...');

const [cnData, ...langDataArray] = await Promise.all([
  fetchLanguageData('cn'),
  ...LANGUAGES.map(lang => fetchLanguageData(lang))
]);

const langDataMap = new Map<Language, AutocompleteItem[]>();
LANGUAGES.forEach((lang, i) => {
  langDataMap.set(lang, langDataArray[i]);
});

function buildTranslations(cnData: AutocompleteItem[], targetData: AutocompleteItem[]): TranslationDictionary {
  const targetByValue = new Map<string, AutocompleteItem>(
    targetData.map(item => [item.value, item])
  );

  const translations: TranslationDictionary = {};

  for (const cnItem of cnData) {
    const { value, label: cnLabel } = cnItem;
    const targetItem = targetByValue.get(value);

    if (targetItem) {
      translations[cnLabel] = targetItem.label;
    }
  }

  return translations;
}

function formatTranslations(translations: TranslationDictionary): string {
  const sortedKeys = Object.keys(translations).sort((a, b) => a.localeCompare(b, 'zh'));
  return sortedKeys.map(key => {
    const value = translations[key];
    const escapedValue = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `  "${key}": "${escapedValue}"`;
  }).join(',\n');
}

const allTranslations: Record<Language, TranslationDictionary> = {} as Record<Language, TranslationDictionary>;

for (const lang of LANGUAGES) {
  const targetData = langDataMap.get(lang)!;
  allTranslations[lang] = buildTranslations(cnData, targetData);
  console.log(`  ${lang}: ${Object.keys(allTranslations[lang]).length} translations`);
}

const langExports = LANGUAGES.map(lang => {
  const content = formatTranslations(allTranslations[lang]);
  return `export const ${lang}Data: Record<string, string> = {\n${content}\n};`;
}).join('\n\n');

const creditPrefix = `// This file is automatically generated. Do not edit manually.
// This data comes from https://tlidb.com/
// Send them your support!
`;

const tsContent = `${creditPrefix}\n${langExports}\n`;

writeFileSync(
  join(srcDir, 'translations.ts'),
  tsContent,
  'utf-8'
);

console.log('Generated translations.ts');
